# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'estoque.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_estoque(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(782, 629)
        Dialog.setStyleSheet("background-color: qlineargradient(spread:reflect, x1:1, y1:0.000227273, x2:1, y2:1, stop:0 rgba(0, 0, 0, 255), stop:0.505263 rgba(198, 176, 135, 255));")
        self.tableWidget = QtWidgets.QTableWidget(Dialog)
        self.tableWidget.setGeometry(QtCore.QRect(80, 160, 675, 381))
        self.tableWidget.setMinimumSize(QtCore.QSize(675, 330))
        self.tableWidget.setMaximumSize(QtCore.QSize(750, 16777215))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        gradient = QtGui.QConicalGradient(0.0, 0.767, 270.3)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(255, 227, 174))
        gradient.setColorAt(0.257895, QtGui.QColor(171, 152, 116, 243))
        gradient.setColorAt(0.331579, QtGui.QColor(171, 152, 116, 243))
        gradient.setColorAt(0.405263, QtGui.QColor(214, 190, 146, 250))
        gradient.setColorAt(0.494737, QtGui.QColor(212, 191, 152, 249))
        gradient.setColorAt(0.505263, QtGui.QColor(126, 112, 86, 237))
        gradient.setColorAt(0.689474, QtGui.QColor(79, 70, 54, 230))
        gradient.setColorAt(1.0, QtGui.QColor(0, 0, 0, 219))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        gradient = QtGui.QConicalGradient(0.0, 0.767, 270.3)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(255, 227, 174))
        gradient.setColorAt(0.257895, QtGui.QColor(171, 152, 116, 243))
        gradient.setColorAt(0.331579, QtGui.QColor(171, 152, 116, 243))
        gradient.setColorAt(0.405263, QtGui.QColor(214, 190, 146, 250))
        gradient.setColorAt(0.494737, QtGui.QColor(212, 191, 152, 249))
        gradient.setColorAt(0.505263, QtGui.QColor(126, 112, 86, 237))
        gradient.setColorAt(0.689474, QtGui.QColor(79, 70, 54, 230))
        gradient.setColorAt(1.0, QtGui.QColor(0, 0, 0, 219))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(198, 176, 135))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(198, 184, 158, 130))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        gradient = QtGui.QConicalGradient(0.0, 0.767, 270.3)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(255, 227, 174))
        gradient.setColorAt(0.257895, QtGui.QColor(171, 152, 116, 243))
        gradient.setColorAt(0.331579, QtGui.QColor(171, 152, 116, 243))
        gradient.setColorAt(0.405263, QtGui.QColor(214, 190, 146, 250))
        gradient.setColorAt(0.494737, QtGui.QColor(212, 191, 152, 249))
        gradient.setColorAt(0.505263, QtGui.QColor(126, 112, 86, 237))
        gradient.setColorAt(0.689474, QtGui.QColor(79, 70, 54, 230))
        gradient.setColorAt(1.0, QtGui.QColor(0, 0, 0, 219))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        gradient = QtGui.QConicalGradient(0.0, 0.767, 270.3)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(255, 227, 174))
        gradient.setColorAt(0.257895, QtGui.QColor(171, 152, 116, 243))
        gradient.setColorAt(0.331579, QtGui.QColor(171, 152, 116, 243))
        gradient.setColorAt(0.405263, QtGui.QColor(214, 190, 146, 250))
        gradient.setColorAt(0.494737, QtGui.QColor(212, 191, 152, 249))
        gradient.setColorAt(0.505263, QtGui.QColor(126, 112, 86, 237))
        gradient.setColorAt(0.689474, QtGui.QColor(79, 70, 54, 230))
        gradient.setColorAt(1.0, QtGui.QColor(0, 0, 0, 219))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(198, 176, 135))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(198, 184, 158, 130))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        gradient = QtGui.QConicalGradient(0.0, 0.767, 270.3)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(255, 227, 174))
        gradient.setColorAt(0.257895, QtGui.QColor(171, 152, 116, 243))
        gradient.setColorAt(0.331579, QtGui.QColor(171, 152, 116, 243))
        gradient.setColorAt(0.405263, QtGui.QColor(214, 190, 146, 250))
        gradient.setColorAt(0.494737, QtGui.QColor(212, 191, 152, 249))
        gradient.setColorAt(0.505263, QtGui.QColor(126, 112, 86, 237))
        gradient.setColorAt(0.689474, QtGui.QColor(79, 70, 54, 230))
        gradient.setColorAt(1.0, QtGui.QColor(0, 0, 0, 219))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        gradient = QtGui.QConicalGradient(0.0, 0.767, 270.3)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(255, 227, 174))
        gradient.setColorAt(0.257895, QtGui.QColor(171, 152, 116, 243))
        gradient.setColorAt(0.331579, QtGui.QColor(171, 152, 116, 243))
        gradient.setColorAt(0.405263, QtGui.QColor(214, 190, 146, 250))
        gradient.setColorAt(0.494737, QtGui.QColor(212, 191, 152, 249))
        gradient.setColorAt(0.505263, QtGui.QColor(126, 112, 86, 237))
        gradient.setColorAt(0.689474, QtGui.QColor(79, 70, 54, 230))
        gradient.setColorAt(1.0, QtGui.QColor(0, 0, 0, 219))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(198, 176, 135))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(198, 184, 158, 130))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.tableWidget.setPalette(palette)
        self.tableWidget.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.tableWidget.setMouseTracking(False)
        self.tableWidget.setTabletTracking(False)
        self.tableWidget.setFocusPolicy(QtCore.Qt.TabFocus)
        self.tableWidget.setAutoFillBackground(True)
        self.tableWidget.setStyleSheet("background-color: qconicalgradient(cx:0, cy:0.767, angle:270.3, stop:0 rgba(255, 227, 174, 255), stop:0.257895 rgba(171, 152, 116, 243), stop:0.331579 rgba(171, 152, 116, 243), stop:0.405263 rgba(214, 190, 146, 250), stop:0.494737 rgba(212, 191, 152, 249), stop:0.505263 rgba(126, 112, 86, 237), stop:0.689474 rgba(79, 70, 54, 230), stop:1 rgba(0, 0, 0, 219));\n"
"font: 81 8pt \"Rockwell Extra Bold\";\n"
"selection-background-color: rgb(198, 176, 135);\n"
"border: 1 solid rgb(198, 176, 135);\n"
"color: rgb(0, 0, 0);\n"
"font-size: 15px;\n"
"\n"
"grid-color: 10;")
        self.tableWidget.setFrameShape(QtWidgets.QFrame.VLine)
        self.tableWidget.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.tableWidget.setLineWidth(1)
        self.tableWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableWidget.setAutoScroll(False)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.AnyKeyPressed)
        self.tableWidget.setTabKeyNavigation(True)
        self.tableWidget.setProperty("showDropIndicator", True)
        self.tableWidget.setDragEnabled(False)
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.ContiguousSelection)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.tableWidget.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.tableWidget.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.tableWidget.setShowGrid(False)
        self.tableWidget.setGridStyle(QtCore.Qt.DotLine)
        self.tableWidget.setWordWrap(True)
        self.tableWidget.setCornerButtonEnabled(True)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setRowCount(11)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        self.tableWidget.horizontalHeader().setVisible(True)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(130)
        self.tableWidget.horizontalHeader().setHighlightSections(False)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(45)
        self.tableWidget.horizontalHeader().setStretchLastSection(False)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(True)
        self.tableWidget.verticalHeader().setMinimumSectionSize(50)
        self.tableWidget.verticalHeader().setSortIndicatorShown(False)
        self.tableWidget.verticalHeader().setStretchLastSection(False)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(70, 110, 681, 51))
        self.label.setStyleSheet("algnment: center;\n"
"font: 81 20pt \"Rockwell Extra Bold\";\n"
"background:rgba(198, 176, 135, 0);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(355, 28, 80, 39))
        font = QtGui.QFont()
        font.setFamily("Algerian")
        font.setPointSize(24)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("background-color: rgb(198, 176, 135,0);\n"
"font: 24pt \"Algerian\";\n"
"\n"
"color: rgb(198, 176, 135);")
        self.label_8.setObjectName("label_8")
        self.label_11 = QtWidgets.QLabel(Dialog)
        self.label_11.setGeometry(QtCore.QRect(422, 17, 51, 41))
        self.label_11.setStyleSheet("background-color: rgb(198, 176, 135,0);\n"
"image: url(:/imgs/icons/manequim.png);")
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setGeometry(QtCore.QRect(310, 20, 55, 41))
        font = QtGui.QFont()
        font.setFamily("MS UI Gothic")
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("background-color: rgb(198, 176, 135,0);\n"
"image: url(:/imgs/icons/guarda-roupa.png);")
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(420, 58, 61, 16))
        self.label_9.setStyleSheet("background-color: rgb(198, 176, 135,0);\n"
"color: rgb(230, 230, 230);\n"
"font: 11pt \"Algerian\";")
        self.label_9.setObjectName("label_9")
        self.voltar = QtWidgets.QPushButton(Dialog)
        self.voltar.setGeometry(QtCore.QRect(30, 90, 41, 31))
        self.voltar.setStyleSheet("background-image: url(:/imgs/seta.png);\n"
"background-color: rgba(255, 255, 255, 0);\n"
"background-repeat: no-repeat;\n"
"font: 81 7pt \"Rockwell Extra Bold\";")
        self.voltar.setText("")
        self.voltar.setObjectName("voltar")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(20, 173, 40, 35))
        self.pushButton_2.setStyleSheet("\n"
"QPushButton {\n"
"    font: 81 7pt \"Rockwell Extra Bold\";\n"
"\n"
"    \n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border-radius: 10;\n"
"    \n"
"    \n"
"    \n"
"    image: url(:/imgs/icons/352005_add_circle_icon.png);\n"
"    font: 81 7pt \"Rockwell Extra Bold\";\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 0, 0, 0.2);\n"
"    border: 5 solid rgb(0, 0, 0, 0);\n"
"\n"
"}\n"
"")
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.remover = QtWidgets.QPushButton(Dialog)
        self.remover.setGeometry(QtCore.QRect(20, 250, 40, 30))
        self.remover.setStyleSheet("\n"
"\n"
"QPushButton {\n"
"    \n"
"    image: url(:/imgs/icons/trash.png);\n"
"    \n"
"    background-color: rgba(255, 255, 255, 0);\n"
"\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 0, 0, 0.2);\n"
"    border: 5 solid rgb(0, 0, 0, 0);\n"
"\n"
"}\n"
"")
        self.remover.setText("")
        self.remover.setObjectName("remover")
        self.atualizar = QtWidgets.QPushButton(Dialog)
        self.atualizar.setGeometry(QtCore.QRect(20, 213, 41, 34))
        self.atualizar.setStyleSheet("\n"
"QPushButton {\n"
"    \n"
"    \n"
"    \n"
"    image: url(:/imgs/icons/processamento-de-dados.png);\n"
"    \n"
"    \n"
"    \n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    \n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 0, 0, 0.2);\n"
"    border: 5 solid rgb(0, 0, 0, 0);\n"
"\n"
"}\n"
"")
        self.atualizar.setText("")
        self.atualizar.setObjectName("atualizar")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(538, 540, 121, 21))
        self.label_2.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"font: 81 10pt \"Rockwell Extra Bold\";")
        self.label_2.setObjectName("label_2")
        self.lcdNumber_2 = QtWidgets.QLCDNumber(Dialog)
        self.lcdNumber_2.setGeometry(QtCore.QRect(660, 540, 81, 23))
        self.lcdNumber_2.setStyleSheet("font: 81 10pt \"Rockwell Extra Bold\";\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.lcdNumber_2.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.lcdNumber_2.setObjectName("lcdNumber_2")
        self.pushButton_3 = QtWidgets.QPushButton(Dialog)
        self.pushButton_3.setGeometry(QtCore.QRect(745, 0, 31, 31))
        self.pushButton_3.setStyleSheet("\n"
"QPushButton {\n"
"    background-color: rgb(255, 170, 0, 0);\n"
"    \n"
"    image: url(:/imgs/icons/fechar.png);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    \n"
"    \n"
"    image: url(:/imgs/icons/fechar_red.png);\n"
"\n"
"}")
        self.pushButton_3.setText("")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_5 = QtWidgets.QPushButton(Dialog)
        self.pushButton_5.setGeometry(QtCore.QRect(720, 0, 25, 31))
        self.pushButton_5.setStyleSheet("\n"
"QPushButton {\n"
"    background-color: rgb(255, 170, 0, 0);\n"
"    \n"
"    image: url(:/imgs/icons/minimize-o-sinal.png);\n"
"    \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    \n"
"    \n"
"    \n"
"    image: url(:/imgs/icons/minimize_red.png);\n"
"    \n"
"}")
        self.pushButton_5.setText("")
        self.pushButton_5.setObjectName("pushButton_5")
        self.remover_2 = QtWidgets.QPushButton(Dialog)
        self.remover_2.setGeometry(QtCore.QRect(20, 285, 40, 30))
        self.remover_2.setStyleSheet("\n"
"\n"
"QPushButton {\n"
"    \n"
"    image: url(:/imgs/icons/8665833_rotate_refresh_icon.png);\n"
"    \n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    \n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 0, 0, 0.2);\n"
"    border: 5 solid rgb(0, 0, 0, 0);\n"
"\n"
"}\n"
"")
        self.remover_2.setText("")
        self.remover_2.setObjectName("remover_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("Dialog", "New Row"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("Dialog", "New Row"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("Dialog", "New Row"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("Dialog", "New Row"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("Dialog", "New Row"))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("Dialog", "New Row"))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("Dialog", "New Row"))
        item = self.tableWidget.verticalHeaderItem(7)
        item.setText(_translate("Dialog", "New Row"))
        item = self.tableWidget.verticalHeaderItem(8)
        item.setText(_translate("Dialog", "New Row"))
        item = self.tableWidget.verticalHeaderItem(9)
        item.setText(_translate("Dialog", "New Row"))
        item = self.tableWidget.verticalHeaderItem(10)
        item.setText(_translate("Dialog", "New Row"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "DESCRIÇAO"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "CÓDIGO"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "TAMANHO"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "PREÇO ($)"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "QUANTIDADE"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Dialog", "TOTAL(R$)"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt;\">Estoque(Disponível)</span></p></body></html>"))
        self.label_8.setText(_translate("Dialog", "Duda"))
        self.label_9.setText(_translate("Dialog", "Fashion"))
        self.label_2.setText(_translate("Dialog", "Valor total (R$):"))
import template.imgs


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_estoque()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
