# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'historico.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_historico(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(875, 549)
        Form.setMinimumSize(QtCore.QSize(875, 549))
        Form.setMaximumSize(QtCore.QSize(875, 549))
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(0, 0, 881, 551))
        self.frame.setMinimumSize(QtCore.QSize(881, 551))
        self.frame.setMaximumSize(QtCore.QSize(881, 551))
        self.frame.setStyleSheet("background-color: qlineargradient(spread:reflect, x1:1, y1:0.000227273, x2:1, y2:1, stop:0 rgba(0, 0, 0, 255), stop:0.605263 rgba(198, 176, 135, 255));\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(50, 175, 221, 131))
        self.label.setStyleSheet("background-color: rgb(198, 176, 135);\n"
"border-right: 5 solid rgba(0, 0, 0, 120);\n"
"border-bottom: 5 solid rgba(0, 0, 0, 120);\n"
"\n"
"")
        self.label.setText("")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(50, 175, 201, 21))
        self.label_2.setStyleSheet("algnment: center;\n"
"background:rgba(198, 176, 135, 0);\n"
"font: 81 11pt \"Rockwell Extra Bold\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(50, 345, 221, 131))
        self.label_3.setStyleSheet("background-color: rgb(198, 176, 135);\n"
"border-right: 5 solid rgba(0, 0, 0, 120);\n"
"border-bottom: 5 solid rgba(0, 0, 0, 120);\n"
"\n"
"")
        self.label_3.setText("")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(50, 345, 89, 43))
        self.label_4.setStyleSheet("algnment: center;\n"
"pedding-left: 30;\n"
"background:rgba(198, 176, 135, 0);\n"
"font: 81 11pt \"Rockwell Extra Bold\";")
        self.label_4.setObjectName("label_4")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(770, 180, 35, 27))
        self.pushButton.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 10;\n"
"    \n"
"    image: url(:/imgs/icons/1608826_search_icon.png);\n"
"    background-color: rgb(0,255,0, 0);\n"
"\n"
"    color: rgb(192, 171, 131);\n"
"    font: 81 7pt \"Rockwell Extra Bold\";\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 0, 0, 0.7);\n"
"\n"
"\n"
"}\n"
"")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.comboBox = QtWidgets.QComboBox(self.frame)
        self.comboBox.setGeometry(QtCore.QRect(590, 185, 121, 22))
        self.comboBox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.dateEdit = QtWidgets.QDateEdit(self.frame)
        self.dateEdit.setGeometry(QtCore.QRect(400, 185, 110, 22))
        self.dateEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.dateEdit.setMinimumDate(QtCore.QDate(2023, 1, 1))
        self.dateEdit.setObjectName("dateEdit")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(50, 225, 201, 31))
        self.label_5.setStyleSheet("algnment: center;\n"
"background:rgba(198, 176, 135, 0);\n"
"font: 81 17pt \"Rockwell Extra Bold\";")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(50, 395, 201, 31))
        self.label_6.setStyleSheet("algnment: center;\n"
"background:rgba(198, 176, 135, 0);\n"
"font: 81 17pt \"Rockwell Extra Bold\";")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(310, 175, 551, 41))
        self.label_7.setStyleSheet("\n"
"QLabel {\n"
"  background-color: rgb(198, 176, 135);\n"
"    font: 81 20pt \"Rockwell Extra Bold\";\n"
"      \n"
"    border-top: 3px solid rgba(0, 0, 0, 120);\n"
"    border-left: 3px solid rgba(0, 0, 0, 120);\n"
"}")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.frame)
        self.tableWidget_2.setGeometry(QtCore.QRect(315, 245, 551, 241))
        self.tableWidget_2.setStyleSheet("QTableWidget {\n"
"    background-color: qlineargradient(spread:reflect, x1:1, y1:0.000227273, x2:1, y2:1, stop:0 rgba(198, 176, 135, 255), stop:0.0157895 rgba(198, 176, 135, 255), stop:0.368421 rgba(125, 111, 85, 255), stop:0.531579 rgba(103, 92, 70, 255), stop:0.878947 rgba(193, 172, 132, 255), stop:1 rgba(99, 88, 67, 255));\n"
"    selection-background-color: rgb(198, 176, 135);\n"
"    selection-color: black;\n"
"    border: none;\n"
"font: 81 11pt \"Rockwell Extra Bold\";\n"
"}\n"
"\n"
"QTableWidget::item:selected {\n"
"    background-color: rgb(198, 176, 135);\n"
"    color: black;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: ;\n"
"    color: rgb(255, 255, 255);\n"
"    color: rgb(158, 140, 108);\n"
"    color: black;\n"
"    padding: 5px;\n"
"    border: none;\n"
"}\n"
"\n"
"QTableWidget::horizontalHeader {\n"
"    background-color: rgb(226, 201, 155);\n"
"    color: rgb(255, 255, 255);\n"
"    color: black;\n"
"    border: none;\n"
"}\n"
"\n"
"\n"
"QTableWidget QScrollBar:vertical {\n"
"    border: none;\n"
"    background-color: #f2f2f2;\n"
"    width: 10px;\n"
"    margin: 0px 0 0px 0;\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.tableWidget_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_2.setAutoScroll(False)
        self.tableWidget_2.setEditTriggers(QtWidgets.QAbstractItemView.AnyKeyPressed|QtWidgets.QAbstractItemView.EditKeyPressed)
        self.tableWidget_2.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget_2.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.tableWidget_2.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.tableWidget_2.setShowGrid(False)
        self.tableWidget_2.setRowCount(0)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        self.tableWidget_2.horizontalHeader().setDefaultSectionSize(180)
        self.tableWidget_2.horizontalHeader().setMinimumSectionSize(180)
        self.tableWidget_2.verticalHeader().setVisible(False)
        self.tableWidget_2.verticalHeader().setDefaultSectionSize(35)
        self.tableWidget_2.verticalHeader().setHighlightSections(True)
        self.label_12 = QtWidgets.QLabel(self.frame)
        self.label_12.setGeometry(QtCore.QRect(90, 100, 681, 51))
        self.label_12.setStyleSheet("algnment: center;\n"
"font: 81 20pt \"Rockwell Extra Bold\";\n"
"background:rgba(198, 176, 135, 0);")
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.label_7.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.pushButton.raise_()
        self.comboBox.raise_()
        self.dateEdit.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.tableWidget_2.raise_()
        self.label_12.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setText(_translate("Form", "Quantidade Vendida:"))
        self.label_4.setText(_translate("Form", "Valor Total: \n"
"(R$)"))
        self.comboBox.setItemText(0, _translate("Form", "Selecionar"))
        self.comboBox.setItemText(1, _translate("Form", "Janeiro"))
        self.comboBox.setItemText(2, _translate("Form", "Fervereiro"))
        self.comboBox.setItemText(3, _translate("Form", "Março"))
        self.comboBox.setItemText(4, _translate("Form", "Abril"))
        self.comboBox.setItemText(5, _translate("Form", "Maio"))
        self.comboBox.setItemText(6, _translate("Form", "Junho"))
        self.comboBox.setItemText(7, _translate("Form", "Julho"))
        self.comboBox.setItemText(8, _translate("Form", "Agosto"))
        self.comboBox.setItemText(9, _translate("Form", "Setembro"))
        self.comboBox.setItemText(10, _translate("Form", "Outubro"))
        self.comboBox.setItemText(11, _translate("Form", "Novembro"))
        self.comboBox.setItemText(12, _translate("Form", "Dezembro"))
        self.dateEdit.setDisplayFormat(_translate("Form", "yyyy"))
        self.label_5.setText(_translate("Form", "0"))
        self.label_6.setText(_translate("Form", "00.0"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("Form", "DESCRIÇÃO"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("Form", "PREÇO"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("Form", "DATA"))
        self.label_12.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; color:#c0ab83;\">HISTORICO DE VENDAS</span></p></body></html>"))
import template.imgs


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_historico()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
