# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Login(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(659, 401)
        Dialog.setMinimumSize(QtCore.QSize(659, 401))
        Dialog.setMaximumSize(QtCore.QSize(659, 401))
        Dialog.setFocusPolicy(QtCore.Qt.TabFocus)
        Dialog.setStyleSheet("\n"
"background-color: qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0, stop:0.5 rgba(0, 0, 0, 255), stop:0.515789 rgba(198, 176, 135, 255));")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 80, 301, 30))
        self.label.setStyleSheet("background-color: rgb(188, 167, 128, 0);\n"
"font: 81 20pt \"Rockwell Extra Bold\";\n"
"\n"
"")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(60, 150, 51, 21))
        self.label_2.setStyleSheet("font: 12pt \"Arial\";\n"
"background-color: rgb(198, 176, 135, .0);\n"
"image: url(:/imgs/icons/user.png);\n"
"")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(60, 190, 51, 20))
        self.label_3.setStyleSheet("font: 75 12pt \"Arial\";\n"
"background-color: rgb(198, 176, 135, 0);\n"
"image: url(:/imgs/icons/lock.png);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(120, 225, 101, 31))
        self.pushButton.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 10;\n"
"    background-color: rgb(0,0,0);\n"
"    border: 5 solid black;\n"
"    color: rgb(192, 171, 131);\n"
"    font: 81 7pt \"Rockwell Extra Bold\";\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 0, 0, 0.7);\n"
"    border: 5 solid rgb(0, 0, 0, 0);\n"
"\n"
"}\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(70, 145, 199, 31))
        self.lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 75 8pt \"Noto Serif\";\n"
"border-radius: 10;\n"
"padding-left: 30;")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_2.setGeometry(QtCore.QRect(70, 185, 201, 31))
        self.lineEdit_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"padding-left: 30;\n"
"border-radius: 10;\n"
"font: 75 8pt \"Noto Serif\";")
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(463, 181, 80, 39))
        font = QtGui.QFont()
        font.setFamily("Algerian")
        font.setPointSize(24)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("background-color: rgb(198, 176, 135,0);\n"
"font: 24pt \"Algerian\";\n"
"\n"
"color: rgb(198, 176, 135);")
        self.label_8.setObjectName("label_8")
        self.label_11 = QtWidgets.QLabel(Dialog)
        self.label_11.setGeometry(QtCore.QRect(530, 170, 51, 41))
        self.label_11.setStyleSheet("background-color: rgb(198, 176, 135,0);\n"
"image: url(:/imgs/icons/manequim.png);")
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(528, 211, 61, 16))
        self.label_9.setStyleSheet("background-color: rgb(198, 176, 135,0);\n"
"color: rgb(230, 230, 230);\n"
"font: 11pt \"Algerian\";")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setGeometry(QtCore.QRect(418, 173, 55, 41))
        font = QtGui.QFont()
        font.setFamily("MS UI Gothic")
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("background-color: rgb(198, 176, 135,0);\n"
"image: url(:/imgs/icons/guarda-roupa.png);")
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.pushButton_3 = QtWidgets.QPushButton(Dialog)
        self.pushButton_3.setGeometry(QtCore.QRect(630, 0, 31, 31))
        self.pushButton_3.setStyleSheet("\n"
"QPushButton {\n"
"    background-color: rgb(255, 170, 0, 0);\n"
"    image: url(:/imgs/icons/fechar.png);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    image: url(:/imgs/icons/fechar_red.png);\n"
"}")
        self.pushButton_3.setText("")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_5 = QtWidgets.QPushButton(Dialog)
        self.pushButton_5.setGeometry(QtCore.QRect(605, 0, 25, 31))
        self.pushButton_5.setStyleSheet("\n"
"QPushButton {\n"
"    background-color: rgb(255, 170, 0, 0);\n"
"    image: url(:/imgs/icons/minimize-o-sinal.png);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    image: url(:/imgs/icons/minimize_red.png);\n"
"}")
        self.pushButton_5.setText("")
        self.pushButton_5.setObjectName("pushButton_5")
        self.label.raise_()
        self.pushButton.raise_()
        self.lineEdit.raise_()
        self.lineEdit_2.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_8.raise_()
        self.label_11.raise_()
        self.label_9.raise_()
        self.label_10.raise_()
        self.pushButton_3.raise_()
        self.pushButton_5.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "LOGIN DO SISTEMA"))
        self.pushButton.setText(_translate("Dialog", "Confirmar"))
        self.lineEdit.setPlaceholderText(_translate("Dialog", "| Digite seu login"))
        self.lineEdit_2.setPlaceholderText(_translate("Dialog", "| Digite sua senha"))
        self.label_8.setText(_translate("Dialog", "Duda"))
        self.label_9.setText(_translate("Dialog", "Fashion"))
import template.imgs


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Login()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
