# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'principal.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(895, 750)
        MainWindow.setMinimumSize(QtCore.QSize(895, 750))
        MainWindow.setMaximumSize(QtCore.QSize(895, 750))
        MainWindow.setStyleSheet("background-color: qlineargradient(spread:reflect, x1:1, y1:0.205, x2:1, y2:0.898, stop:0.0315789 rgba(71, 59, 38, 255), stop:0.278947 rgba(103, 92, 70, 255), stop:0.568421 rgba(125, 111, 85, 255), stop:0.98421 rgba(198, 176, 135, 255), stop:1 rgba(198, 176, 135, 255));")
        MainWindow.setAnimated(True)
        MainWindow.setDocumentMode(False)
        MainWindow.setDockOptions(QtWidgets.QMainWindow.AllowNestedDocks|QtWidgets.QMainWindow.AllowTabbedDocks|QtWidgets.QMainWindow.AnimatedDocks)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.estoque = QtWidgets.QFrame(self.centralwidget)
        self.estoque.setGeometry(QtCore.QRect(20, 100, 921, 571))
        self.estoque.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.estoque.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.estoque.setFrameShadow(QtWidgets.QFrame.Raised)
        self.estoque.setObjectName("estoque")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.estoque)
        self.tableWidget_2.setGeometry(QtCore.QRect(130, 90, 685, 431))
        self.tableWidget_2.setMinimumSize(QtCore.QSize(675, 330))
        self.tableWidget_2.setMaximumSize(QtCore.QSize(685, 16777215))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        gradient = QtGui.QConicalGradient(0.0, 0.767, 270.3)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(255, 227, 174))
        gradient.setColorAt(0.257895, QtGui.QColor(171, 152, 116, 243))
        gradient.setColorAt(0.331579, QtGui.QColor(171, 152, 116, 243))
        gradient.setColorAt(0.405263, QtGui.QColor(214, 190, 146, 250))
        gradient.setColorAt(0.494737, QtGui.QColor(212, 191, 152, 249))
        gradient.setColorAt(0.505263, QtGui.QColor(126, 112, 86, 237))
        gradient.setColorAt(0.689474, QtGui.QColor(79, 70, 54, 230))
        gradient.setColorAt(1.0, QtGui.QColor(0, 0, 0, 219))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        gradient = QtGui.QConicalGradient(0.0, 0.767, 270.3)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(255, 227, 174))
        gradient.setColorAt(0.257895, QtGui.QColor(171, 152, 116, 243))
        gradient.setColorAt(0.331579, QtGui.QColor(171, 152, 116, 243))
        gradient.setColorAt(0.405263, QtGui.QColor(214, 190, 146, 250))
        gradient.setColorAt(0.494737, QtGui.QColor(212, 191, 152, 249))
        gradient.setColorAt(0.505263, QtGui.QColor(126, 112, 86, 237))
        gradient.setColorAt(0.689474, QtGui.QColor(79, 70, 54, 230))
        gradient.setColorAt(1.0, QtGui.QColor(0, 0, 0, 219))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(198, 176, 135))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(198, 184, 158, 130))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        gradient = QtGui.QConicalGradient(0.0, 0.767, 270.3)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(255, 227, 174))
        gradient.setColorAt(0.257895, QtGui.QColor(171, 152, 116, 243))
        gradient.setColorAt(0.331579, QtGui.QColor(171, 152, 116, 243))
        gradient.setColorAt(0.405263, QtGui.QColor(214, 190, 146, 250))
        gradient.setColorAt(0.494737, QtGui.QColor(212, 191, 152, 249))
        gradient.setColorAt(0.505263, QtGui.QColor(126, 112, 86, 237))
        gradient.setColorAt(0.689474, QtGui.QColor(79, 70, 54, 230))
        gradient.setColorAt(1.0, QtGui.QColor(0, 0, 0, 219))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        gradient = QtGui.QConicalGradient(0.0, 0.767, 270.3)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(255, 227, 174))
        gradient.setColorAt(0.257895, QtGui.QColor(171, 152, 116, 243))
        gradient.setColorAt(0.331579, QtGui.QColor(171, 152, 116, 243))
        gradient.setColorAt(0.405263, QtGui.QColor(214, 190, 146, 250))
        gradient.setColorAt(0.494737, QtGui.QColor(212, 191, 152, 249))
        gradient.setColorAt(0.505263, QtGui.QColor(126, 112, 86, 237))
        gradient.setColorAt(0.689474, QtGui.QColor(79, 70, 54, 230))
        gradient.setColorAt(1.0, QtGui.QColor(0, 0, 0, 219))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(198, 176, 135))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(198, 184, 158, 130))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        gradient = QtGui.QConicalGradient(0.0, 0.767, 270.3)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(255, 227, 174))
        gradient.setColorAt(0.257895, QtGui.QColor(171, 152, 116, 243))
        gradient.setColorAt(0.331579, QtGui.QColor(171, 152, 116, 243))
        gradient.setColorAt(0.405263, QtGui.QColor(214, 190, 146, 250))
        gradient.setColorAt(0.494737, QtGui.QColor(212, 191, 152, 249))
        gradient.setColorAt(0.505263, QtGui.QColor(126, 112, 86, 237))
        gradient.setColorAt(0.689474, QtGui.QColor(79, 70, 54, 230))
        gradient.setColorAt(1.0, QtGui.QColor(0, 0, 0, 219))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        gradient = QtGui.QConicalGradient(0.0, 0.767, 270.3)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(255, 227, 174))
        gradient.setColorAt(0.257895, QtGui.QColor(171, 152, 116, 243))
        gradient.setColorAt(0.331579, QtGui.QColor(171, 152, 116, 243))
        gradient.setColorAt(0.405263, QtGui.QColor(214, 190, 146, 250))
        gradient.setColorAt(0.494737, QtGui.QColor(212, 191, 152, 249))
        gradient.setColorAt(0.505263, QtGui.QColor(126, 112, 86, 237))
        gradient.setColorAt(0.689474, QtGui.QColor(79, 70, 54, 230))
        gradient.setColorAt(1.0, QtGui.QColor(0, 0, 0, 219))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(198, 176, 135))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(198, 184, 158, 130))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.tableWidget_2.setPalette(palette)
        self.tableWidget_2.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.tableWidget_2.setMouseTracking(False)
        self.tableWidget_2.setTabletTracking(False)
        self.tableWidget_2.setFocusPolicy(QtCore.Qt.TabFocus)
        self.tableWidget_2.setAutoFillBackground(True)
        self.tableWidget_2.setStyleSheet("background-color: qconicalgradient(cx:0, cy:0.767, angle:270.3, stop:0 rgba(255, 227, 174, 255), stop:0.257895 rgba(171, 152, 116, 243), stop:0.331579 rgba(171, 152, 116, 243), stop:0.405263 rgba(214, 190, 146, 250), stop:0.494737 rgba(212, 191, 152, 249), stop:0.505263 rgba(126, 112, 86, 237), stop:0.689474 rgba(79, 70, 54, 230), stop:1 rgba(0, 0, 0, 219));\n"
"font: 75 8pt \"Noto Serif\";\n"
"selection-background-color: rgb(198, 176, 135);\n"
"border: 1 solid rgb(198, 176, 135);\n"
"color: rgb(0, 0, 0);\n"
"font-size: 15px;\n"
"\n"
"grid-color: 10;")
        self.tableWidget_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.tableWidget_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.tableWidget_2.setLineWidth(1)
        self.tableWidget_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget_2.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableWidget_2.setAutoScroll(False)
        self.tableWidget_2.setEditTriggers(QtWidgets.QAbstractItemView.AnyKeyPressed)
        self.tableWidget_2.setTabKeyNavigation(True)
        self.tableWidget_2.setProperty("showDropIndicator", True)
        self.tableWidget_2.setDragEnabled(False)
        self.tableWidget_2.setAlternatingRowColors(True)
        self.tableWidget_2.setSelectionMode(QtWidgets.QAbstractItemView.ContiguousSelection)
        self.tableWidget_2.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget_2.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.tableWidget_2.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.tableWidget_2.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.tableWidget_2.setShowGrid(False)
        self.tableWidget_2.setGridStyle(QtCore.Qt.DotLine)
        self.tableWidget_2.setWordWrap(True)
        self.tableWidget_2.setCornerButtonEnabled(True)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(6)
        self.tableWidget_2.setRowCount(11)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(5, item)
        self.tableWidget_2.horizontalHeader().setVisible(True)
        self.tableWidget_2.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget_2.horizontalHeader().setDefaultSectionSize(110)
        self.tableWidget_2.horizontalHeader().setHighlightSections(False)
        self.tableWidget_2.horizontalHeader().setMinimumSectionSize(45)
        self.tableWidget_2.horizontalHeader().setStretchLastSection(False)
        self.tableWidget_2.verticalHeader().setVisible(False)
        self.tableWidget_2.verticalHeader().setCascadingSectionResizes(True)
        self.tableWidget_2.verticalHeader().setMinimumSectionSize(50)
        self.tableWidget_2.verticalHeader().setSortIndicatorShown(False)
        self.tableWidget_2.verticalHeader().setStretchLastSection(False)
        self.label_12 = QtWidgets.QLabel(self.estoque)
        self.label_12.setGeometry(QtCore.QRect(60, 40, 821, 51))
        self.label_12.setStyleSheet("algnment: center;\n"
"font: 75 20pt \"Noto Serif\";\n"
"\n"
"\n"
"background:rgba(198, 176, 135, 0);")
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.label_22 = QtWidgets.QLabel(self.estoque)
        self.label_22.setGeometry(QtCore.QRect(70, 90, 51, 201))
        self.label_22.setStyleSheet("\n"
"background-color: rgb(213, 190, 148);\n"
"\n"
"border-right: 5 solid rgb(199, 176, 135);\n"
"border-bottom: 5 solid rgb(199, 176, 135);\n"
"")
        self.label_22.setText("")
        self.label_22.setObjectName("label_22")
        self.pushButton_6 = QtWidgets.QPushButton(self.estoque)
        self.pushButton_6.setGeometry(QtCore.QRect(67, 92, 51, 41))
        self.pushButton_6.setStyleSheet("\n"
"QPushButton {\n"
"    font: 81 7pt \"Rockwell Extra Bold\";\n"
"\n"
"    \n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border-radius: 10;\n"
"    \n"
"    \n"
"    \n"
"    image: url(:/imgs/icons/352005_add_circle_icon.png);\n"
"    font: 81 7pt \"Rockwell Extra Bold\";\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 0, 0, 0.2);\n"
"    border: 5 solid rgb(0, 0, 0, 0);\n"
"\n"
"}\n"
"")
        self.pushButton_6.setText("")
        self.pushButton_6.setObjectName("pushButton_6")
        self.atualizar = QtWidgets.QPushButton(self.estoque)
        self.atualizar.setGeometry(QtCore.QRect(67, 142, 51, 41))
        self.atualizar.setStyleSheet("\n"
"QPushButton {\n"
"    \n"
"    \n"
"    \n"
"    image: url(:/imgs/icons/processamento-de-dados.png);\n"
"    \n"
"    \n"
"    \n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    \n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 0, 0, 0.2);\n"
"    border: 5 solid rgb(0, 0, 0, 0);\n"
"\n"
"}\n"
"")
        self.atualizar.setText("")
        self.atualizar.setObjectName("atualizar")
        self.remover = QtWidgets.QPushButton(self.estoque)
        self.remover.setGeometry(QtCore.QRect(67, 192, 51, 41))
        self.remover.setStyleSheet("\n"
"\n"
"QPushButton {\n"
"    \n"
"    image: url(:/imgs/icons/trash.png);\n"
"    \n"
"    background-color: rgba(255, 255, 255, 0);\n"
"\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 0, 0, 0.2);\n"
"    border: 5 solid rgb(0, 0, 0, 0);\n"
"\n"
"}\n"
"")
        self.remover.setText("")
        self.remover.setObjectName("remover")
        self.remover_2 = QtWidgets.QPushButton(self.estoque)
        self.remover_2.setGeometry(QtCore.QRect(71, 242, 41, 41))
        self.remover_2.setStyleSheet("\n"
"\n"
"QPushButton {\n"
"    \n"
"    image: url(:/imgs/icons/8665833_rotate_refresh_icon.png);\n"
"    \n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    \n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 0, 0, 0.2);\n"
"    border: 5 solid rgb(0, 0, 0, 0);\n"
"\n"
"}\n"
"")
        self.remover_2.setText("")
        self.remover_2.setObjectName("remover_2")
        self.label_13 = QtWidgets.QLabel(self.estoque)
        self.label_13.setGeometry(QtCore.QRect(560, 530, 121, 21))
        self.label_13.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"font: 75 11pt \"Noto Serif\";")
        self.label_13.setObjectName("label_13")
        self.label_7 = QtWidgets.QLabel(self.estoque)
        self.label_7.setGeometry(QtCore.QRect(680, 525, 136, 31))
        self.label_7.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 75 10pt \"Noto Serif\";\n"
"border: 2 solid grey;\n"
"")
        self.label_7.setObjectName("label_7")
        self.avender = QtWidgets.QFrame(self.centralwidget)
        self.avender.setGeometry(QtCore.QRect(2000, 100, 871, 551))
        self.avender.setStyleSheet("background:rgba(255, 255, 255, 0);\n"
"border-radius: 30;")
        self.avender.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.avender.setFrameShadow(QtWidgets.QFrame.Raised)
        self.avender.setObjectName("avender")
        self.label = QtWidgets.QLabel(self.avender)
        self.label.setGeometry(QtCore.QRect(-10, -10, 901, 31))
        self.label.setStyleSheet("algnment: center;\n"
"background:rgba(198, 176, 135, 0);\n"
"font: 75 20pt \"Noto Serif\";")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.avender)
        self.lineEdit_2.setGeometry(QtCore.QRect(110, 40, 191, 31))
        self.lineEdit_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-style: outset;\n"
"border-color: #0066A2;\n"
"border-radius: 10;\n"
"background-color: rgb(255, 255, 255);\n"
"border-style: outset;\n"
"border-color: #0066A2;\n"
"padding-left: 30;\n"
"font: 81 7pt \"Rockwell Extra Bold\";")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton = QtWidgets.QPushButton(self.avender)
        self.pushButton.setGeometry(QtCore.QRect(310, 40, 41, 31))
        self.pushButton.setStyleSheet("QPushButton {\n"
"\n"
"    border-radius: 10;\n"
"    \n"
"    background-color: rgba(111, 99, 76, 0);\n"
"\n"
"\n"
"    font: 81 7pt \"Rockwell Extra Bold\";\n"
"    \n"
"    image: url(:/imgs/icons/1608826_search_icon.png);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 0, 0, 0.2);\n"
"    border: 2 solid rgb(0, 0, 0, 0);\n"
"\n"
"}\n"
"")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.tableWidget = QtWidgets.QTableWidget(self.avender)
        self.tableWidget.setGeometry(QtCore.QRect(100, 90, 685, 215))
        self.tableWidget.setMinimumSize(QtCore.QSize(685, 215))
        self.tableWidget.setMaximumSize(QtCore.QSize(760, 16777215))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        gradient = QtGui.QConicalGradient(0.0, 0.5, 270.3)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(255, 227, 174))
        gradient.setColorAt(0.257895, QtGui.QColor(171, 152, 116, 243))
        gradient.setColorAt(0.331579, QtGui.QColor(171, 152, 116, 243))
        gradient.setColorAt(0.405263, QtGui.QColor(214, 190, 146, 250))
        gradient.setColorAt(0.494737, QtGui.QColor(212, 191, 152, 249))
        gradient.setColorAt(0.505263, QtGui.QColor(126, 112, 86, 237))
        gradient.setColorAt(0.689474, QtGui.QColor(79, 70, 54, 230))
        gradient.setColorAt(1.0, QtGui.QColor(0, 0, 0, 219))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        gradient = QtGui.QConicalGradient(0.0, 0.5, 270.3)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(255, 227, 174))
        gradient.setColorAt(0.257895, QtGui.QColor(171, 152, 116, 243))
        gradient.setColorAt(0.331579, QtGui.QColor(171, 152, 116, 243))
        gradient.setColorAt(0.405263, QtGui.QColor(214, 190, 146, 250))
        gradient.setColorAt(0.494737, QtGui.QColor(212, 191, 152, 249))
        gradient.setColorAt(0.505263, QtGui.QColor(126, 112, 86, 237))
        gradient.setColorAt(0.689474, QtGui.QColor(79, 70, 54, 230))
        gradient.setColorAt(1.0, QtGui.QColor(0, 0, 0, 219))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(198, 176, 135))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(198, 184, 158, 130))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        gradient = QtGui.QConicalGradient(0.0, 0.5, 270.3)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(255, 227, 174))
        gradient.setColorAt(0.257895, QtGui.QColor(171, 152, 116, 243))
        gradient.setColorAt(0.331579, QtGui.QColor(171, 152, 116, 243))
        gradient.setColorAt(0.405263, QtGui.QColor(214, 190, 146, 250))
        gradient.setColorAt(0.494737, QtGui.QColor(212, 191, 152, 249))
        gradient.setColorAt(0.505263, QtGui.QColor(126, 112, 86, 237))
        gradient.setColorAt(0.689474, QtGui.QColor(79, 70, 54, 230))
        gradient.setColorAt(1.0, QtGui.QColor(0, 0, 0, 219))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        gradient = QtGui.QConicalGradient(0.0, 0.5, 270.3)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(255, 227, 174))
        gradient.setColorAt(0.257895, QtGui.QColor(171, 152, 116, 243))
        gradient.setColorAt(0.331579, QtGui.QColor(171, 152, 116, 243))
        gradient.setColorAt(0.405263, QtGui.QColor(214, 190, 146, 250))
        gradient.setColorAt(0.494737, QtGui.QColor(212, 191, 152, 249))
        gradient.setColorAt(0.505263, QtGui.QColor(126, 112, 86, 237))
        gradient.setColorAt(0.689474, QtGui.QColor(79, 70, 54, 230))
        gradient.setColorAt(1.0, QtGui.QColor(0, 0, 0, 219))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(198, 176, 135))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(198, 184, 158, 130))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        gradient = QtGui.QConicalGradient(0.0, 0.5, 270.3)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(255, 227, 174))
        gradient.setColorAt(0.257895, QtGui.QColor(171, 152, 116, 243))
        gradient.setColorAt(0.331579, QtGui.QColor(171, 152, 116, 243))
        gradient.setColorAt(0.405263, QtGui.QColor(214, 190, 146, 250))
        gradient.setColorAt(0.494737, QtGui.QColor(212, 191, 152, 249))
        gradient.setColorAt(0.505263, QtGui.QColor(126, 112, 86, 237))
        gradient.setColorAt(0.689474, QtGui.QColor(79, 70, 54, 230))
        gradient.setColorAt(1.0, QtGui.QColor(0, 0, 0, 219))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        gradient = QtGui.QConicalGradient(0.0, 0.5, 270.3)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(255, 227, 174))
        gradient.setColorAt(0.257895, QtGui.QColor(171, 152, 116, 243))
        gradient.setColorAt(0.331579, QtGui.QColor(171, 152, 116, 243))
        gradient.setColorAt(0.405263, QtGui.QColor(214, 190, 146, 250))
        gradient.setColorAt(0.494737, QtGui.QColor(212, 191, 152, 249))
        gradient.setColorAt(0.505263, QtGui.QColor(126, 112, 86, 237))
        gradient.setColorAt(0.689474, QtGui.QColor(79, 70, 54, 230))
        gradient.setColorAt(1.0, QtGui.QColor(0, 0, 0, 219))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(198, 176, 135))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(198, 184, 158, 130))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.tableWidget.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Noto Serif")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        font.setKerning(False)
        self.tableWidget.setFont(font)
        self.tableWidget.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.tableWidget.setMouseTracking(False)
        self.tableWidget.setTabletTracking(False)
        self.tableWidget.setFocusPolicy(QtCore.Qt.TabFocus)
        self.tableWidget.setAutoFillBackground(False)
        self.tableWidget.setStyleSheet("background-color: qconicalgradient(cx:0, cy:0.5, angle:270.3, stop:0 rgba(255, 227, 174, 255), stop:0.257895 rgba(171, 152, 116, 243), stop:0.331579 rgba(171, 152, 116, 243), stop:0.405263 rgba(214, 190, 146, 250), stop:0.494737 rgba(212, 191, 152, 249), stop:0.505263 rgba(126, 112, 86, 237), stop:0.689474 rgba(79, 70, 54, 230), stop:1 rgba(0, 0, 0, 219));\n"
"font: 75 12pt \"Noto Serif\";\n"
"selection-background-color: rgb(198, 176, 135);\n"
"border: 1 solid rgb(198, 176, 135);\n"
"color: rgb(0, 0, 0);\n"
"font-size: 15px;\n"
"border-radius: 0;\n"
"grid-color: 10;")
        self.tableWidget.setInputMethodHints(QtCore.Qt.ImhNone)
        self.tableWidget.setFrameShape(QtWidgets.QFrame.Panel)
        self.tableWidget.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.tableWidget.setLineWidth(1)
        self.tableWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.tableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.tableWidget.setAutoScroll(True)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setTabKeyNavigation(False)
        self.tableWidget.setProperty("showDropIndicator", True)
        self.tableWidget.setDragEnabled(True)
        self.tableWidget.setAlternatingRowColors(False)
        self.tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget.setTextElideMode(QtCore.Qt.ElideNone)
        self.tableWidget.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.tableWidget.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setGridStyle(QtCore.Qt.NoPen)
        self.tableWidget.setWordWrap(True)
        self.tableWidget.setCornerButtonEnabled(True)
        self.tableWidget.setRowCount(0)
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        item.setFont(font)
        item.setBackground(QtGui.QColor(0, 0, 0, 0))
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.tableWidget.horizontalHeader().setVisible(True)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(220)
        self.tableWidget.horizontalHeader().setHighlightSections(False)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(150)
        self.tableWidget.horizontalHeader().setStretchLastSection(False)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(False)
        self.tableWidget.verticalHeader().setDefaultSectionSize(40)
        self.tableWidget.verticalHeader().setHighlightSections(True)
        self.tableWidget.verticalHeader().setMinimumSectionSize(40)
        self.tableWidget.verticalHeader().setSortIndicatorShown(False)
        self.tableWidget.verticalHeader().setStretchLastSection(False)
        self.pushButton_4 = QtWidgets.QPushButton(self.avender)
        self.pushButton_4.setGeometry(QtCore.QRect(680, 40, 51, 31))
        self.pushButton_4.setStyleSheet("QPushButton {\n"
"    border-radius: 10;\n"
"    background-color: rgb(0,0,0,0);\n"
"\n"
"    \n"
"    image: url(:/imgs/icons/cancelamento.png);\n"
"\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    \n"
"    \n"
"    background-color: rgb(153, 0, 0,0);\n"
"    border: 5 solid rgb(0, 0, 0, 0);\n"
"\n"
"}\n"
"")
        self.pushButton_4.setText("")
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_4 = QtWidgets.QLabel(self.avender)
        self.label_4.setGeometry(QtCore.QRect(640, 307, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"font: 81 10pt \"Rockwell Extra Bold\";")
        self.label_4.setObjectName("label_4")
        self.pushButton_2 = QtWidgets.QPushButton(self.avender)
        self.pushButton_2.setGeometry(QtCore.QRect(730, 40, 61, 31))
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    \n"
"    border-radius: 10;\n"
"    background-color: rgb(0,85,0,0);\n"
"    image: url(:/imgs/icons/confirme.png);\n"
"    \n"
"\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    \n"
"    background-color: rgb(0, 85, 0, 0);\n"
"    border: 5 solid rgb(0, 0, 0, 0);\n"
"\n"
"}\n"
"")
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_3 = QtWidgets.QLabel(self.avender)
        self.label_3.setGeometry(QtCore.QRect(114, 45, 31, 21))
        self.label_3.setStyleSheet("image: url(:/imgs/icons/leitor-de-codigos-de-barra.png);\n"
"background-color: rgb(198, 176, 135,0);\n"
"")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.lcdNumber = QtWidgets.QLCDNumber(self.avender)
        self.lcdNumber.setGeometry(QtCore.QRect(690, 310, 81, 23))
        self.lcdNumber.setStyleSheet("\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.lcdNumber.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lcdNumber.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.lcdNumber.setObjectName("lcdNumber")
        self.label_2 = QtWidgets.QLabel(self.avender)
        self.label_2.setGeometry(QtCore.QRect(100, 30, 701, 51))
        self.label_2.setStyleSheet("background-color: rgb(198, 176, 135);\n"
"border-right: 4 solid  rgb(133, 118, 90);\n"
"border-bottom: 4 solid  rgb(133, 118, 90);\n"
"")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.frame_2 = QtWidgets.QFrame(self.avender)
        self.frame_2.setGeometry(QtCore.QRect(100, 350, 691, 171))
        self.frame_2.setStyleSheet("background-color: rgb(198, 176, 135);\n"
"border-right: 4 solid  rgb(133, 118, 90);\n"
"border-bottom: 4 solid  rgb(133, 118, 90);\n"
"border-radius: 0;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setGeometry(QtCore.QRect(0, -1, 671, 41))
        self.label_5.setStyleSheet("border: 0 solid;\n"
"font: 75 20pt \"Noto Serif\";")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_3.setGeometry(QtCore.QRect(360, 50, 61, 31))
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"    \n"
"    border-radius: 10;\n"
"    \n"
"    image: url(:/imgs/icons/dinheiro.png);\n"
"    color: rgb(255, 255, 255,0 );\n"
"    \n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 0, 0, 0.7);\n"
"    border: 5 solid rgb(0, 0, 0, 0);\n"
"\n"
"}\n"
"")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_5.setGeometry(QtCore.QRect(270, 50, 61, 31))
        self.pushButton_5.setStyleSheet("QPushButton {\n"
"    \n"
"    border-radius: 10;\n"
"    \n"
"    \n"
"    image: url(:/imgs/icons/forma-de-pagamento.png);\n"
"    color: rgb(255, 255, 255,0);\n"
"    \n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 0, 0, 0.7);\n"
"    border: 5 solid rgb(0, 0, 0, 0);\n"
"\n"
"}\n"
"")
        self.pushButton_5.setObjectName("pushButton_5")
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.frame_2)
        self.doubleSpinBox.setGeometry(QtCore.QRect(270, 50, 141, 31))
        self.doubleSpinBox.setStyleSheet("border: 0 solid;\n"
"border-left: 2 solid rgb(143, 143, 143);\n"
"border-top: 2 solid rgb(143, 143, 143);\n"
"\n"
"background: white;")
        self.doubleSpinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox.setMaximum(500005.99)
        self.doubleSpinBox.setSingleStep(6.0)
        self.doubleSpinBox.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.doubleSpinBox.setProperty("value", 0.0)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.label_9 = QtWidgets.QLabel(self.frame_2)
        self.label_9.setGeometry(QtCore.QRect(440, 0, 141, 51))
        self.label_9.setStyleSheet("\n"
"background-repeat: no-repeat;\n"
"\n"
"background-color: rgb(255, 255, 255, 0);\n"
"\n"
"border: 0 solid;\n"
"image: url(:/imgs/icons/caixas.png);")
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.frame_2)
        self.label_10.setGeometry(QtCore.QRect(120, 0, 71, 51))
        self.label_10.setStyleSheet("\n"
"background-repeat: no-repeat;\n"
"\n"
"background-color: rgb(255, 255, 255, 0);\n"
"\n"
"border: 0 solid;\n"
"image: url(:/imgs/icons/caixas.png);")
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.pushButton_13 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_13.setGeometry(QtCore.QRect(250, 130, 191, 31))
        self.pushButton_13.setStyleSheet("QPushButton {\n"
"    \n"
"    border-radius: 10;\n"
"    \n"
"    image: url(:/imgs/icons/troca-de-dinheiro.png);\n"
"    color: rgb(255, 255, 255,0);\n"
"    \n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 0, 0, 0.7);\n"
"    border: 5 solid rgb(0, 0, 0, 0);\n"
"\n"
"}\n"
"")
        self.pushButton_13.setObjectName("pushButton_13")
        self.troco = QtWidgets.QLabel(self.frame_2)
        self.troco.setGeometry(QtCore.QRect(250, 90, 181, 31))
        self.troco.setStyleSheet("border: 0 solid;\n"
"font: 75 12pt \"Noto Serif\";")
        self.troco.setText("")
        self.troco.setAlignment(QtCore.Qt.AlignCenter)
        self.troco.setObjectName("troco")
        self.pushButton_16 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_16.setGeometry(QtCore.QRect(490, 130, 191, 31))
        self.pushButton_16.setStyleSheet("QPushButton {\n"
"\n"
"    \n"
"    border-radius: 10;\n"
"    \n"
"    \n"
"    image: url(:/imgs/icons/confirme_compra.png);\n"
"    color: rgb(255, 255, 255,0);\n"
"    \n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 0, 0, 0.7);\n"
"    border: 5 solid rgb(0, 0, 0, 0);\n"
"\n"
"}\n"
"")
        self.pushButton_16.setObjectName("pushButton_16")
        self.pushButton_17 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_17.setGeometry(QtCore.QRect(10, 130, 191, 31))
        self.pushButton_17.setStyleSheet("QPushButton {\n"
"\n"
"    \n"
"    border-radius: 10;\n"
"    \n"
"        image: url(:/imgs/icons/seta.png);\n"
"    color: rgb(255, 255, 255,0);\n"
"    \n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 0, 0, 0.7);\n"
"    border: 5 solid rgb(0, 0, 0, 0);\n"
"\n"
"}\n"
"")
        self.pushButton_17.setObjectName("pushButton_17")
        self.troco.raise_()
        self.doubleSpinBox.raise_()
        self.label_5.raise_()
        self.pushButton_5.raise_()
        self.label_9.raise_()
        self.label_10.raise_()
        self.pushButton_13.raise_()
        self.pushButton_3.raise_()
        self.pushButton_16.raise_()
        self.pushButton_17.raise_()
        self.label_2.raise_()
        self.label.raise_()
        self.lineEdit_2.raise_()
        self.pushButton.raise_()
        self.tableWidget.raise_()
        self.pushButton_4.raise_()
        self.label_4.raise_()
        self.pushButton_2.raise_()
        self.label_3.raise_()
        self.lcdNumber.raise_()
        self.frame_2.raise_()
        self.historico = QtWidgets.QFrame(self.centralwidget)
        self.historico.setGeometry(QtCore.QRect(2000, 70, 861, 551))
        self.historico.setMinimumSize(QtCore.QSize(300, 551))
        self.historico.setMaximumSize(QtCore.QSize(881, 551))
        self.historico.setStyleSheet("\n"
"background-color: rgba(255, 255, 255, 0);")
        self.historico.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.historico.setFrameShadow(QtWidgets.QFrame.Raised)
        self.historico.setObjectName("historico")
        self.label_14 = QtWidgets.QLabel(self.historico)
        self.label_14.setGeometry(QtCore.QRect(80, 175, 201, 131))
        self.label_14.setStyleSheet("background-color: rgb(198, 176, 135);\n"
"border-right: 5 solid rgba(0, 0, 0, 120);\n"
"border-bottom: 5 solid rgba(0, 0, 0, 120);\n"
"\n"
"")
        self.label_14.setText("")
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.historico)
        self.label_15.setGeometry(QtCore.QRect(80, 175, 201, 21))
        self.label_15.setStyleSheet("algnment: center;\n"
"background:rgba(198, 176, 135, 0);\n"
"\n"
"font: 75 12pt \"Noto Serif\";")
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.historico)
        self.label_16.setGeometry(QtCore.QRect(80, 360, 201, 131))
        self.label_16.setStyleSheet("background-color: rgb(198, 176, 135);\n"
"border-right: 5 solid rgba(0, 0, 0, 120);\n"
"border-bottom: 5 solid rgba(0, 0, 0, 120);\n"
"\n"
"")
        self.label_16.setText("")
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.historico)
        self.label_17.setGeometry(QtCore.QRect(80, 360, 201, 43))
        self.label_17.setStyleSheet("algnment: center;\n"
"pedding-left: 30;\n"
"background:rgba(198, 176, 135, 0);\n"
"font: 75 12pt \"Noto Serif\";")
        self.label_17.setObjectName("label_17")
        self.pushButton_7 = QtWidgets.QPushButton(self.historico)
        self.pushButton_7.setGeometry(QtCore.QRect(770, 180, 35, 27))
        self.pushButton_7.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 10;\n"
"    \n"
"    image: url(:/imgs/icons/1608826_search_icon.png);\n"
"    background-color: rgb(0,255,0, 0);\n"
"\n"
"    color: rgb(192, 171, 131);\n"
"    font: 81 7pt \"Rockwell Extra Bold\";\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 0, 0, 0.7);\n"
"\n"
"\n"
"}\n"
"")
        self.pushButton_7.setText("")
        self.pushButton_7.setObjectName("pushButton_7")
        self.comboBox = QtWidgets.QComboBox(self.historico)
        self.comboBox.setGeometry(QtCore.QRect(590, 185, 121, 22))
        self.comboBox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.dateEdit = QtWidgets.QDateEdit(self.historico)
        self.dateEdit.setGeometry(QtCore.QRect(400, 185, 110, 22))
        self.dateEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.dateEdit.setMinimumDate(QtCore.QDate(2023, 1, 1))
        self.dateEdit.setObjectName("dateEdit")
        self.label_18 = QtWidgets.QLabel(self.historico)
        self.label_18.setGeometry(QtCore.QRect(80, 225, 201, 31))
        self.label_18.setStyleSheet("algnment: center;\n"
"background:rgba(198, 176, 135, 0);\n"
"font: 75 16pt \"Noto Serif\";")
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.historico)
        self.label_19.setGeometry(QtCore.QRect(80, 410, 201, 31))
        self.label_19.setStyleSheet("algnment: center;\n"
"background:rgba(198, 176, 135, 0);\n"
"font: 75 16pt \"Noto Serif\";")
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.historico)
        self.label_20.setGeometry(QtCore.QRect(310, 175, 551, 41))
        self.label_20.setStyleSheet("\n"
"QLabel {\n"
"  background-color: rgb(198, 176, 135);\n"
"    font: 81 20pt \"Rockwell Extra Bold\";\n"
"      \n"
"    border-bottom: 3px solid rgba(0, 0, 0, 120);\n"
"    border-right: 3px solid rgba(0, 0, 0, 120);\n"
"}")
        self.label_20.setText("")
        self.label_20.setObjectName("label_20")
        self.tableWidget_3 = QtWidgets.QTableWidget(self.historico)
        self.tableWidget_3.setGeometry(QtCore.QRect(320, 250, 541, 241))
        self.tableWidget_3.setStyleSheet("QTableWidget {\n"
"    background-color: qlineargradient(spread:reflect, x1:1, y1:0.000227273, x2:1, y2:1, stop:0 rgba(198, 176, 135, 255), stop:0.0157895 rgba(198, 176, 135, 255), stop:0.368421 rgba(125, 111, 85, 255), stop:0.531579 rgba(103, 92, 70, 255), stop:0.878947 rgba(193, 172, 132, 255), stop:1 rgba(99, 88, 67, 255));\n"
"    selection-background-color: rgb(198, 176, 135);\n"
"    selection-color: black;\n"
"    border: none;\n"
"    font: 75 12pt \"Noto Serif\";\n"
"    border-right: 5 solid rgba(0, 0, 0, 120);\n"
"    border-bottom: 5 solid rgba(0, 0, 0, 120);\n"
"}\n"
"\n"
"QTableWidget::item:selected {\n"
"    background-color: rgb(198, 176, 135);\n"
"    color: black;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: ;\n"
"    color: rgb(255, 255, 255);\n"
"    color: rgb(158, 140, 108);\n"
"    color: black;\n"
"    padding: 5px;\n"
"    border: none;\n"
"}\n"
"\n"
"QTableWidget::horizontalHeader {\n"
"    background-color: rgb(226, 201, 155);\n"
"    color: rgb(255, 255, 255);\n"
"    color: black;\n"
"    border: none;\n"
"}\n"
"\n"
"\n"
"QTableWidget QScrollBar:vertical {\n"
"    border: none;\n"
"    background-color: #f2f2f2;\n"
"    width: 10px;\n"
"    margin: 0px 0 0px 0;\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.tableWidget_3.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_3.setAutoScroll(False)
        self.tableWidget_3.setEditTriggers(QtWidgets.QAbstractItemView.AnyKeyPressed|QtWidgets.QAbstractItemView.EditKeyPressed)
        self.tableWidget_3.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget_3.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.tableWidget_3.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.tableWidget_3.setShowGrid(False)
        self.tableWidget_3.setRowCount(0)
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(2, item)
        self.tableWidget_3.horizontalHeader().setDefaultSectionSize(180)
        self.tableWidget_3.horizontalHeader().setMinimumSectionSize(180)
        self.tableWidget_3.verticalHeader().setVisible(False)
        self.tableWidget_3.verticalHeader().setDefaultSectionSize(35)
        self.tableWidget_3.verticalHeader().setHighlightSections(True)
        self.label_21 = QtWidgets.QLabel(self.historico)
        self.label_21.setGeometry(QtCore.QRect(70, 100, 821, 51))
        self.label_21.setStyleSheet("algnment: center;\n"
"font: 75 16pt \"Noto Serif\";\n"
"background:rgba(198, 176, 135, 0);")
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.label_14.raise_()
        self.label_15.raise_()
        self.label_16.raise_()
        self.label_17.raise_()
        self.label_18.raise_()
        self.label_19.raise_()
        self.label_20.raise_()
        self.tableWidget_3.raise_()
        self.label_21.raise_()
        self.comboBox.raise_()
        self.dateEdit.raise_()
        self.pushButton_7.raise_()
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(-10, -20, 91, 351))
        self.frame.setStyleSheet("border-right: 1.5 solid black;\n"
"border-bottom: 1.5 solid black;\n"
"background-color: qradialgradient(spread:repeat, cx:0.5, cy:0.5, radius:1.294, fx:0.5, fy:0.5, stop:0 rgba(193, 170, 119, 255), stop:0.226316 rgba(154, 136, 96, 255), stop:1 rgba(31, 27, 19, 255));\n"
"border-radius: 30;\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.pushButton_12 = QtWidgets.QPushButton(self.frame)
        self.pushButton_12.setGeometry(QtCore.QRect(-20, 100, 121, 41))
        self.pushButton_12.setStyleSheet("QPushButton {\n"
"\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border-bottom: 0;\n"
"    \n"
"    image: url(:/imgs/icons/silhueta-de-icone-de-casa.png);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 0, 0, 0.2);\n"
"    border: 5 solid rgb(0, 0, 0, 0);\n"
"}")
        self.pushButton_12.setText("")
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_10 = QtWidgets.QPushButton(self.frame)
        self.pushButton_10.setGeometry(QtCore.QRect(-20, 268, 121, 51))
        self.pushButton_10.setStyleSheet("\n"
"QPushButton {\n"
"\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    image: url(:/imgs/icons/estoque-pronto.png);\n"
"border-bottom: 0;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 0, 0, 0.2);\n"
"    border: 5 solid rgb(0, 0, 0, 0);\n"
"}")
        self.pushButton_10.setText("")
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(self.frame)
        self.pushButton_11.setGeometry(QtCore.QRect(-20, 215, 121, 41))
        self.pushButton_11.setStyleSheet("QPushButton {\n"
"\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    image: url(:/imgs/icons/rolagem.png);\n"
"border-bottom: 0;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 0, 0, 0.2);\n"
"    border: 5 solid rgb(0, 0, 0, 0);\n"
"}")
        self.pushButton_11.setText("")
        self.pushButton_11.setObjectName("pushButton_11")
        self.fecharmenu = QtWidgets.QPushButton(self.frame)
        self.fecharmenu.setGeometry(QtCore.QRect(-20, 20, 121, 41))
        self.fecharmenu.setStyleSheet("QPushButton {\n"
"\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border-bottom: 0;\n"
"    image: url(:/imgs/icons/352145_storage_icon.png);\n"
"\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 0, 0, 0.2);\n"
"    border: 5 solid rgb(0, 0, 0, 0);\n"
"}")
        self.fecharmenu.setText("")
        self.fecharmenu.setObjectName("fecharmenu")
        self.pushButton_14 = QtWidgets.QPushButton(self.frame)
        self.pushButton_14.setGeometry(QtCore.QRect(-17, 150, 121, 51))
        self.pushButton_14.setStyleSheet("QPushButton {\n"
"\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    \n"
"    image: url(:/imgs/icons/adicionar.png);\n"
"border-bottom: 0;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 0, 0, 0.2);\n"
"    border: 5 solid rgb(0, 0, 0, 0);\n"
"}")
        self.pushButton_14.setText("")
        self.pushButton_14.setObjectName("pushButton_14")
        self.showmenu = QtWidgets.QPushButton(self.centralwidget)
        self.showmenu.setGeometry(QtCore.QRect(0, 0, 51, 31))
        self.showmenu.setStyleSheet("QPushButton {\n"
"\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border-bottom: 0;\n"
"    image: url(:/imgs/icons/352145_storage_icon.png);\n"
"\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 0, 0, 0.2);\n"
"    border: 5 solid rgb(0, 0, 0, 0);\n"
"}")
        self.showmenu.setText("")
        self.showmenu.setObjectName("showmenu")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(0, 0, 905, 771))
        self.label_6.setStyleSheet("background-image: url(:/imgs/icons/fu.png);")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.pushButton_15 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_15.setGeometry(QtCore.QRect(300, 10, 281, 101))
        self.pushButton_15.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.pushButton_15.setText("")
        self.pushButton_15.setObjectName("pushButton_15")
        self.label_6.raise_()
        self.showmenu.raise_()
        self.estoque.raise_()
        self.avender.raise_()
        self.historico.raise_()
        self.frame.raise_()
        self.pushButton_15.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.actionAtualizar = QtWidgets.QAction(MainWindow)
        self.actionAtualizar.setCheckable(False)
        self.actionAtualizar.setChecked(False)
        self.actionAtualizar.setEnabled(True)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/imgs/icons/8665833_rotate_refresh_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAtualizar.setIcon(icon)
        self.actionAtualizar.setStatusTip("")
        self.actionAtualizar.setShortcutVisibleInContextMenu(True)
        self.actionAtualizar.setObjectName("actionAtualizar")
        self.actionApagar = QtWidgets.QAction(MainWindow)
        self.actionApagar.setCheckable(True)
        self.actionApagar.setEnabled(True)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/imgs/icons/trash.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionApagar.setIcon(icon1)
        self.actionApagar.setObjectName("actionApagar")
        self.actionProcurar = QtWidgets.QAction(MainWindow)
        self.actionProcurar.setEnabled(True)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/imgs/icons/1608826_search_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionProcurar.setIcon(icon2)
        self.actionProcurar.setAutoRepeat(True)
        self.actionProcurar.setObjectName("actionProcurar")
        self.actionCadastrar = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/imgs/icons/352005_add_circle_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCadastrar.setIcon(icon3)
        self.actionCadastrar.setObjectName("actionCadastrar")
        self.hist = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/imgs/icons/8673512_ic_fluent_mail_edit_filled_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.hist.setIcon(icon4)
        self.hist.setObjectName("hist")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tableWidget_2.setSortingEnabled(False)
        item = self.tableWidget_2.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_2.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_2.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_2.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_2.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_2.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_2.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_2.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_2.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_2.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_2.verticalHeaderItem(10)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "DESCRIÇAO"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "CÓDIGO"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "TAMANHO"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "PREÇO ($)"))
        item = self.tableWidget_2.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "QUANTIDADE"))
        item = self.tableWidget_2.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "TOTAL(R$)"))
        self.label_12.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt; font-weight:600;\">Estoque(Disponível)</span></p><p align=\"center\"><br/></p></body></html>"))
        self.label_13.setText(_translate("MainWindow", "Valor total (R$):"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\"><br/></p></body></html>"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p>Vendas</p><p><br/></p></body></html>"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "| Código do produto"))
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "CÓDIGO"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "NOME"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "PREÇO"))
        self.label_4.setText(_translate("MainWindow", "Total:"))
        self.label_5.setText(_translate("MainWindow", "Confirmar compra"))
        self.pushButton_3.setText(_translate("MainWindow", "cash"))
        self.pushButton_5.setText(_translate("MainWindow", "cartao"))
        self.pushButton_13.setText(_translate("MainWindow", "gerar"))
        self.pushButton_16.setText(_translate("MainWindow", "gerar"))
        self.pushButton_17.setText(_translate("MainWindow", "gerar"))
        self.label_15.setText(_translate("MainWindow", "  Quantidade Vendida:"))
        self.label_17.setText(_translate("MainWindow", "       Valor Total: (R$)"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Selecionar"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Janeiro"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Fervereiro"))
        self.comboBox.setItemText(3, _translate("MainWindow", "Março"))
        self.comboBox.setItemText(4, _translate("MainWindow", "Abril"))
        self.comboBox.setItemText(5, _translate("MainWindow", "Maio"))
        self.comboBox.setItemText(6, _translate("MainWindow", "Junho"))
        self.comboBox.setItemText(7, _translate("MainWindow", "Julho"))
        self.comboBox.setItemText(8, _translate("MainWindow", "Agosto"))
        self.comboBox.setItemText(9, _translate("MainWindow", "Setembro"))
        self.comboBox.setItemText(10, _translate("MainWindow", "Outubro"))
        self.comboBox.setItemText(11, _translate("MainWindow", "Novembro"))
        self.comboBox.setItemText(12, _translate("MainWindow", "Dezembro"))
        self.dateEdit.setDisplayFormat(_translate("MainWindow", "yyyy"))
        self.label_18.setText(_translate("MainWindow", "0"))
        self.label_19.setText(_translate("MainWindow", "00.0"))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "DESCRIÇÃO"))
        item = self.tableWidget_3.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "PREÇO"))
        item = self.tableWidget_3.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "DATA"))
        self.label_21.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:22pt; color:#000000;\">HISTÓRICO DE VENDAS</span></p></body></html>"))
        self.actionAtualizar.setText(_translate("MainWindow", "Atualizar"))
        self.actionAtualizar.setToolTip(_translate("MainWindow", "Atualizar produtos"))
        self.actionApagar.setText(_translate("MainWindow", "Apagar"))
        self.actionApagar.setToolTip(_translate("MainWindow", "Apagar produtos"))
        self.actionProcurar.setText(_translate("MainWindow", "Procurar"))
        self.actionProcurar.setToolTip(_translate("MainWindow", "Procurar produtos"))
        self.actionCadastrar.setText(_translate("MainWindow", "Cadastrar"))
        self.hist.setText(_translate("MainWindow", "Histórico"))
        self.hist.setToolTip(_translate("MainWindow", "Histórico de vendas"))
import template.imgs


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
