# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'registro.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Registrar(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(600, 600)
        Dialog.setMinimumSize(QtCore.QSize(600, 600))
        Dialog.setMaximumSize(QtCore.QSize(600, 600))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Historic")
        font.setPointSize(20)
        Dialog.setFont(font)
        Dialog.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        Dialog.setWindowOpacity(12.0)
        Dialog.setAutoFillBackground(False)
        Dialog.setStyleSheet("")
        Dialog.setSizeGripEnabled(False)
        Dialog.setModal(False)
        self.reg = QtWidgets.QFrame(Dialog)
        self.reg.setGeometry(QtCore.QRect(80, 80, 461, 431))
        self.reg.setStyleSheet("\n"
"border-radius: 50;\n"
"\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(199, 176, 135, 255), stop:1 rgba(31, 31, 31, 255));")
        self.reg.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.reg.setFrameShadow(QtWidgets.QFrame.Raised)
        self.reg.setObjectName("reg")
        self.label_2 = QtWidgets.QLabel(self.reg)
        self.label_2.setEnabled(True)
        self.label_2.setGeometry(QtCore.QRect(130, 100, 41, 21))
        self.label_2.setStyleSheet("image: url(:/imgs/icons/8673512_ic_fluent_mail_edit_filled_icon.png);\n"
"background-color: rgb(198, 176, 135,0);\n"
"")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_11 = QtWidgets.QLabel(self.reg)
        self.label_11.setGeometry(QtCore.QRect(259, 329, 51, 41))
        self.label_11.setStyleSheet("image: url(:/imgs/icons/manequim.png);\n"
"background-color: rgb(198, 176, 135,0);")
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.label_10 = QtWidgets.QLabel(self.reg)
        self.label_10.setGeometry(QtCore.QRect(147, 332, 55, 41))
        self.label_10.setStyleSheet("image: url(:/imgs/icons/guarda-roupa.png);\n"
"background-color: rgb(198, 176, 135,0);")
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.label_12 = QtWidgets.QLabel(self.reg)
        self.label_12.setGeometry(QtCore.QRect(130, 260, 41, 21))
        self.label_12.setStyleSheet("background-color: rgb(198, 176, 135,0);\n"
"image: url(:/imgs/icons/caixas.png);\n"
"")
        self.label_12.setText("")
        self.label_12.setObjectName("label_12")
        self.label_6 = QtWidgets.QLabel(self.reg)
        self.label_6.setGeometry(QtCore.QRect(128, 220, 41, 21))
        self.label_6.setStyleSheet("image: url(:/imgs/icons/usd-circle.png);\n"
"background-color: rgb(198, 176, 135,0);\n"
"")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.label_9 = QtWidgets.QLabel(self.reg)
        self.label_9.setGeometry(QtCore.QRect(247, 370, 71, 16))
        self.label_9.setStyleSheet("background-color: rgb(198, 176, 135,0);\n"
"color: rgb(230, 230, 230);\n"
"font: 11pt \"Algerian\";")
        self.label_9.setObjectName("label_9")
        self.lineEdit = QtWidgets.QLineEdit(self.reg)
        self.lineEdit.setGeometry(QtCore.QRect(130, 94, 191, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-style: outset;\n"
"border-color: #0066A2;\n"
"border-radius: 10;\n"
"background-color: rgb(255, 255, 255);\n"
"border-style: outset;\n"
"border-color: #0066A2;\n"
"padding-left: 30;\n"
"font: 75 8pt \"Noto Serif\";")
        self.lineEdit.setText("")
        self.lineEdit.setClearButtonEnabled(False)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.reg)
        self.lineEdit_2.setGeometry(QtCore.QRect(130, 134, 191, 31))
        self.lineEdit_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-style: outset;\n"
"border-color: #0066A2;\n"
"border-radius: 10;\n"
"background-color: rgb(255, 255, 255);\n"
"border-style: outset;\n"
"border-color: #0066A2;\n"
"padding-left: 30;\n"
"font: 75 8pt \"Noto Serif\";")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label = QtWidgets.QLabel(self.reg)
        self.label.setGeometry(QtCore.QRect(-20, 35, 500, 51))
        self.label.setMinimumSize(QtCore.QSize(440, 50))
        self.label.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(10)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label.setFont(font)
        self.label.setAutoFillBackground(False)
        self.label.setStyleSheet("font: 81 20pt \"Rockwell Extra Bold\";\n"
"background-color: rgb(198, 176, 135,0);\n"
"\n"
"")
        self.label.setTextFormat(QtCore.Qt.RichText)
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.sendbutton = QtWidgets.QPushButton(self.reg)
        self.sendbutton.setEnabled(True)
        self.sendbutton.setGeometry(QtCore.QRect(170, 290, 101, 28))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(7)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        font.setKerning(False)
        self.sendbutton.setFont(font)
        self.sendbutton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.sendbutton.setMouseTracking(False)
        self.sendbutton.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 10;\n"
"    background-color: rgb(0,0,0);\n"
"    border: 5 solid black;\n"
"    color: rgb(192, 171, 131);\n"
"    font: 81 7pt \"Rockwell Extra Bold\";\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 0, 0, 0.7);\n"
"    border: 5 solid rgb(0, 0, 0, 0);\n"
"\n"
"}\n"
"")
        self.sendbutton.setInputMethodHints(QtCore.Qt.ImhNone)
        self.sendbutton.setAutoDefault(False)
        self.sendbutton.setObjectName("sendbutton")
        self.label_3 = QtWidgets.QLabel(self.reg)
        self.label_3.setGeometry(QtCore.QRect(130, 140, 41, 21))
        self.label_3.setStyleSheet("image: url(:/imgs/icons/leitor-de-codigos-de-barra.png);\n"
"background-color: rgb(198, 176, 135,0);\n"
"")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(self.reg)
        self.label_5.setGeometry(QtCore.QRect(129, 180, 41, 21))
        self.label_5.setStyleSheet("image: url(:/imgs/icons/icons8-tamanho-original-30.png);\n"
"background-color: rgb(198, 176, 135,0);\n"
"")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.reg)
        self.lineEdit_3.setGeometry(QtCore.QRect(130, 174, 191, 31))
        self.lineEdit_3.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-style: outset;\n"
"border-color: #0066A2;\n"
"border-radius: 10;\n"
"background-color: rgb(255, 255, 255);\n"
"border-style: outset;\n"
"border-color: #0066A2;\n"
"padding-left: 30;\n"
"font: 75 8pt \"Noto Serif\";")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_8 = QtWidgets.QLabel(self.reg)
        self.label_8.setGeometry(QtCore.QRect(192, 340, 80, 38))
        font = QtGui.QFont()
        font.setFamily("Algerian")
        font.setPointSize(24)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("background-color: rgb(198, 176, 135,0);\n"
"font: 24pt \"Algerian\";\n"
"color: rgb(0, 0, 0);")
        self.label_8.setObjectName("label_8")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.reg)
        self.lineEdit_5.setGeometry(QtCore.QRect(130, 254, 191, 31))
        self.lineEdit_5.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-style: outset;\n"
"border-color: #0066A2;\n"
"border-radius: 10;\n"
"background-color: rgb(255, 255, 255);\n"
"border-style: outset;\n"
"border-color: #0066A2;\n"
"padding-left: 30;\n"
"font: 75 8pt \"Noto Serif\";")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.reg)
        self.lineEdit_4.setGeometry(QtCore.QRect(130, 214, 191, 31))
        self.lineEdit_4.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-style: outset;\n"
"border-color: #0066A2;\n"
"border-radius: 10;\n"
"background-color: rgb(255, 255, 255);\n"
"border-style: outset;\n"
"border-color: #0066A2;\n"
"padding-left: 30;\n"
"font: 75 8pt \"Noto Serif\";")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_11.raise_()
        self.label_10.raise_()
        self.label_9.raise_()
        self.lineEdit.raise_()
        self.lineEdit_2.raise_()
        self.label.raise_()
        self.sendbutton.raise_()
        self.label_3.raise_()
        self.lineEdit_3.raise_()
        self.label_8.raise_()
        self.lineEdit_5.raise_()
        self.lineEdit_4.raise_()
        self.label_6.raise_()
        self.label_5.raise_()
        self.label_2.raise_()
        self.label_12.raise_()
        self.atua = QtWidgets.QFrame(Dialog)
        self.atua.setGeometry(QtCore.QRect(80, 80, 441, 401))
        self.atua.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(199, 176, 135, 255), stop:1 rgba(31, 31, 31, 255));\n"
"border-radius: 50;")
        self.atua.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.atua.setFrameShadow(QtWidgets.QFrame.Raised)
        self.atua.setObjectName("atua")
        self.sendbutton_2 = QtWidgets.QPushButton(self.atua)
        self.sendbutton_2.setEnabled(True)
        self.sendbutton_2.setGeometry(QtCore.QRect(163, 251, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(7)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        font.setKerning(False)
        self.sendbutton_2.setFont(font)
        self.sendbutton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.sendbutton_2.setMouseTracking(False)
        self.sendbutton_2.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 10;\n"
"    background-color: rgb(0,0,0);\n"
"    border: 5 solid black;\n"
"    color: rgb(192, 171, 131);\n"
"    font: 81 7pt \"Rockwell Extra Bold\";\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 0, 0, 0.7);\n"
"    border: 5 solid rgb(0, 0, 0, 0);\n"
"\n"
"}\n"
"")
        self.sendbutton_2.setInputMethodHints(QtCore.Qt.ImhNone)
        self.sendbutton_2.setAutoDefault(False)
        self.sendbutton_2.setObjectName("sendbutton_2")
        self.label_13 = QtWidgets.QLabel(self.atua)
        self.label_13.setGeometry(QtCore.QRect(119, 209, 51, 21))
        self.label_13.setStyleSheet("background-color: rgb(198, 176, 135,0);\n"
"image: url(:/imgs/icons/caixas.png);")
        self.label_13.setText("")
        self.label_13.setObjectName("label_13")
        self.label_15 = QtWidgets.QLabel(self.atua)
        self.label_15.setGeometry(QtCore.QRect(192, 330, 80, 38))
        font = QtGui.QFont()
        font.setFamily("Algerian")
        font.setPointSize(24)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("background-color: rgb(198, 176, 135,0);\n"
"font: 24pt \"Algerian\";\n"
"color: rgb(0, 0, 0);")
        self.label_15.setObjectName("label_15")
        self.label_18 = QtWidgets.QLabel(self.atua)
        self.label_18.setGeometry(QtCore.QRect(247, 360, 71, 16))
        self.label_18.setStyleSheet("background-color: rgb(198, 176, 135,0);\n"
"color: rgb(230, 230, 230);\n"
"font: 11pt \"Algerian\";")
        self.label_18.setObjectName("label_18")
        self.codi_at = QtWidgets.QLineEdit(self.atua)
        self.codi_at.setGeometry(QtCore.QRect(128, 124, 191, 31))
        self.codi_at.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-style: outset;\n"
"border-color: #0066A2;\n"
"border-radius: 10;\n"
"background-color: rgb(255, 255, 255);\n"
"border-style: outset;\n"
"border-color: #0066A2;\n"
"padding-left: 30;\n"
"font: 81 7pt \"Rockwell Extra Bold\";")
        self.codi_at.setObjectName("codi_at")
        self.label_16 = QtWidgets.QLabel(self.atua)
        self.label_16.setGeometry(QtCore.QRect(119, 170, 51, 21))
        self.label_16.setStyleSheet("image: url(:/imgs/icons/usd-circle.png);\n"
"background-color: rgb(198, 176, 135,0);\n"
"")
        self.label_16.setText("")
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.atua)
        self.label_17.setGeometry(QtCore.QRect(0, 40, 441, 51))
        self.label_17.setMinimumSize(QtCore.QSize(440, 50))
        self.label_17.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(10)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_17.setFont(font)
        self.label_17.setAutoFillBackground(False)
        self.label_17.setStyleSheet("font: 81 20pt \"Rockwell Extra Bold\";\n"
"background-color: rgb(198, 176, 135,0);\n"
"\n"
"")
        self.label_17.setTextFormat(QtCore.Qt.RichText)
        self.label_17.setScaledContents(False)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.label_14 = QtWidgets.QLabel(self.atua)
        self.label_14.setGeometry(QtCore.QRect(257, 319, 51, 41))
        self.label_14.setStyleSheet("image: url(:/imgs/icons/manequim.png);\n"
"background-color: rgb(198, 176, 135,0);")
        self.label_14.setText("")
        self.label_14.setObjectName("label_14")
        self.pre_at = QtWidgets.QLineEdit(self.atua)
        self.pre_at.setGeometry(QtCore.QRect(128, 164, 191, 31))
        self.pre_at.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-style: outset;\n"
"border-color: #0066A2;\n"
"border-radius: 10;\n"
"background-color: rgb(255, 255, 255);\n"
"border-style: outset;\n"
"border-color: #0066A2;\n"
"padding-left: 30;\n"
"font: 81 7pt \"Rockwell Extra Bold\";")
        self.pre_at.setObjectName("pre_at")
        self.label_19 = QtWidgets.QLabel(self.atua)
        self.label_19.setGeometry(QtCore.QRect(147, 322, 55, 41))
        self.label_19.setStyleSheet("image: url(:/imgs/icons/guarda-roupa.png);\n"
"background-color: rgb(198, 176, 135,0);")
        self.label_19.setText("")
        self.label_19.setObjectName("label_19")
        self.label_4 = QtWidgets.QLabel(self.atua)
        self.label_4.setGeometry(QtCore.QRect(130, 129, 31, 21))
        self.label_4.setStyleSheet("image: url(:/imgs/icons/leitor-de-codigos-de-barra.png);\n"
"background-color: rgb(198, 176, 135,0);\n"
"")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.quant_at = QtWidgets.QLineEdit(self.atua)
        self.quant_at.setGeometry(QtCore.QRect(128, 204, 191, 31))
        self.quant_at.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-style: outset;\n"
"border-color: #0066A2;\n"
"border-radius: 10;\n"
"background-color: rgb(255, 255, 255);\n"
"border-style: outset;\n"
"border-color: #0066A2;\n"
"padding-left: 30;\n"
"font: 81 7pt \"Rockwell Extra Bold\";")
        self.quant_at.setObjectName("quant_at")
        self.sendbutton_2.raise_()
        self.label_15.raise_()
        self.label_18.raise_()
        self.codi_at.raise_()
        self.label_17.raise_()
        self.label_14.raise_()
        self.pre_at.raise_()
        self.label_19.raise_()
        self.label_4.raise_()
        self.label_16.raise_()
        self.quant_at.raise_()
        self.label_13.raise_()
        self.remover = QtWidgets.QFrame(Dialog)
        self.remover.setGeometry(QtCore.QRect(90, 80, 421, 391))
        self.remover.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(199, 176, 135, 255), stop:1 rgba(31, 31, 31, 255));\n"
"border-radius: 50;")
        self.remover.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.remover.setFrameShadow(QtWidgets.QFrame.Raised)
        self.remover.setObjectName("remover")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.remover)
        self.lineEdit_9.setGeometry(QtCore.QRect(115, 150, 191, 31))
        self.lineEdit_9.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-style: outset;\n"
"border-color: #0066A2;\n"
"border-radius: 10;\n"
"background-color: rgb(255, 255, 255);\n"
"border-style: outset;\n"
"border-color: #0066A2;\n"
"padding-left: 30;\n"
"font: 81 7pt \"Rockwell Extra Bold\";")
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.label_21 = QtWidgets.QLabel(self.remover)
        self.label_21.setGeometry(QtCore.QRect(242, 277, 51, 41))
        self.label_21.setStyleSheet("image: url(:/imgs/icons/manequim.png);\n"
"background-color: rgb(198, 176, 135,0);")
        self.label_21.setText("")
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.remover)
        self.label_22.setGeometry(QtCore.QRect(175, 288, 80, 38))
        font = QtGui.QFont()
        font.setFamily("Algerian")
        font.setPointSize(24)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_22.setFont(font)
        self.label_22.setStyleSheet("background-color: rgb(198, 176, 135,0);\n"
"font: 24pt \"Algerian\";\n"
"color: rgb(0, 0, 0);")
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.remover)
        self.label_23.setGeometry(QtCore.QRect(118, 155, 31, 21))
        self.label_23.setStyleSheet("image: url(:/imgs/icons/leitor-de-codigos-de-barra.png);\n"
"background-color: rgb(198, 176, 135,0);\n"
"")
        self.label_23.setText("")
        self.label_23.setObjectName("label_23")
        self.label_25 = QtWidgets.QLabel(self.remover)
        self.label_25.setGeometry(QtCore.QRect(0, 40, 421, 51))
        self.label_25.setMinimumSize(QtCore.QSize(300, 50))
        self.label_25.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(10)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_25.setFont(font)
        self.label_25.setAutoFillBackground(False)
        self.label_25.setStyleSheet("font: 81 20pt \"Rockwell Extra Bold\";\n"
"background-color: rgb(198, 176, 135,0);\n"
"\n"
"")
        self.label_25.setTextFormat(QtCore.Qt.RichText)
        self.label_25.setScaledContents(False)
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.remover)
        self.label_26.setGeometry(QtCore.QRect(230, 318, 71, 16))
        self.label_26.setStyleSheet("background-color: rgb(198, 176, 135,0);\n"
"color: rgb(230, 230, 230);\n"
"font: 11pt \"Algerian\";")
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.remover)
        self.label_27.setGeometry(QtCore.QRect(130, 280, 55, 41))
        self.label_27.setStyleSheet("image: url(:/imgs/icons/guarda-roupa.png);\n"
"background-color: rgb(198, 176, 135,0);")
        self.label_27.setText("")
        self.label_27.setObjectName("label_27")
        self.sendbutton_3 = QtWidgets.QPushButton(self.remover)
        self.sendbutton_3.setEnabled(True)
        self.sendbutton_3.setGeometry(QtCore.QRect(150, 200, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(7)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        font.setKerning(False)
        self.sendbutton_3.setFont(font)
        self.sendbutton_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.sendbutton_3.setMouseTracking(False)
        self.sendbutton_3.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 10;\n"
"    background-color: rgb(0,0,0);\n"
"    border: 5 solid black;\n"
"    color: rgb(192, 171, 131);\n"
"    font: 81 7pt \"Rockwell Extra Bold\";\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 0, 0, 0.7);\n"
"    border: 5 solid rgb(0, 0, 0, 0);\n"
"\n"
"}\n"
"")
        self.sendbutton_3.setInputMethodHints(QtCore.Qt.ImhNone)
        self.sendbutton_3.setAutoDefault(False)
        self.sendbutton_3.setObjectName("sendbutton_3")
        self.fundo = QtWidgets.QLabel(Dialog)
        self.fundo.setGeometry(QtCore.QRect(-40, -150, 911, 761))
        self.fundo.setStyleSheet("background-image: url(:/imgs/icons/fu.png);")
        self.fundo.setText("")
        self.fundo.setObjectName("fundo")
        self.backbutton = QtWidgets.QPushButton(Dialog)
        self.backbutton.setGeometry(QtCore.QRect(30, 20, 71, 28))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(7)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.backbutton.setFont(font)
        self.backbutton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.backbutton.setMouseTracking(False)
        self.backbutton.setStyleSheet("QPushButton {\n"
"    \n"
"    \n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    font: 81 7pt \"Rockwell Extra Bold\";\n"
"    color: rgb(192, 171, 131);\n"
"    border-radius: 10;\n"
"    \n"
"    \n"
"    image: url(:/imgs/icons/seta.png);\n"
"    \n"
"\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 0, 0, 0.7);\n"
"    border: 5 solid rgb(0, 0, 0, 0);\n"
"\n"
"}\n"
"\n"
"")
        self.backbutton.setInputMethodHints(QtCore.Qt.ImhNone)
        self.backbutton.setText("")
        self.backbutton.setObjectName("backbutton")
        self.fundo.raise_()
        self.remover.raise_()
        self.atua.raise_()
        self.reg.raise_()
        self.backbutton.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_9.setText(_translate("Dialog", "Fashion"))
        self.lineEdit.setPlaceholderText(_translate("Dialog", "| Descrição do produto"))
        self.lineEdit_2.setPlaceholderText(_translate("Dialog", "|Código do produto"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:20pt; font-weight:600;\">REGISTRO DE PRODUTOS</span></p></body></html>"))
        self.sendbutton.setText(_translate("Dialog", "Enviar"))
        self.lineEdit_3.setPlaceholderText(_translate("Dialog", "|Tamanho do produto"))
        self.label_8.setText(_translate("Dialog", "Duda"))
        self.lineEdit_5.setPlaceholderText(_translate("Dialog", "|Quantidade de peças"))
        self.lineEdit_4.setPlaceholderText(_translate("Dialog", "|Preço do produto"))
        self.sendbutton_2.setText(_translate("Dialog", "Enviar"))
        self.label_15.setText(_translate("Dialog", "Duda"))
        self.label_18.setText(_translate("Dialog", "Fashion"))
        self.codi_at.setPlaceholderText(_translate("Dialog", "|Código do produto"))
        self.label_17.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600;\">ATUALIZAR PRODUTO</span></p></body></html>"))
        self.pre_at.setPlaceholderText(_translate("Dialog", "|Preço do produto"))
        self.quant_at.setPlaceholderText(_translate("Dialog", "|Quantidade de peças"))
        self.lineEdit_9.setPlaceholderText(_translate("Dialog", "|Código do produto"))
        self.label_22.setText(_translate("Dialog", "Duda"))
        self.label_25.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600;\">DELETAR PRODUTO</span></p></body></html>"))
        self.label_26.setText(_translate("Dialog", "Fashion"))
        self.sendbutton_3.setText(_translate("Dialog", "DELETAR"))
import template.imgs


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Registrar()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
